struct UpdateFlasher150files {
	char	*inname;
	char	*outname;
} UpdateFlasher150files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/1.50 Update Flasher/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/extprxs.elf", "kd/extprxs.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/restore.elf", "kd/restore.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/updateflasher.elf", "kd/updateflasher.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/decryptprx.prx", "kd/decryptprx.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/ta082_driver.prx", "kd/ta082_driver.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"}
};
struct DC3files {
	char	*inname;
	char	*outname;
} DC3files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC3/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/DC3/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC3/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC3/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC3/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC3/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC3/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC3/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC4files {
	char	*inname;
	char	*outname;
} DC4files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC4/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/DC4/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC4/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC4/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC4/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC4/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC4/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC4/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC5files {
	char	*inname;
	char	*outname;
} DC5files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC5/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC5/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC5/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC5/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC5/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC5/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC5/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC5/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC7files {
	char	*inname;
	char	*outname;
} DC7files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC7/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC7/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DC7/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DC7/tmctrl401.prx", "tmctrl401.prx"},
	{"Magic Memory Stick/DC7/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DC7/kd/galaxy.prx", "kd/galaxy.prx"},
	{"Magic Memory Stick/DC7/kd/idcanager.prx", "kd/idcanager.prx"},
	{"Magic Memory Stick/DC7/kd/idsregeneration.prx", "kd/idsregeneration.prx"},
	{"Magic Memory Stick/DC7/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DC7/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DC7/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DC7/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC7/kd/march33.prx", "kd/march33.prx"},
	{"Magic Memory Stick/DC7/kd/popcorn.prx", "kd/popcorn.prx"},
	{"Magic Memory Stick/DC7/kd/pspbtdnf.bin", "kd/pspbtdnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtdnf_02g.bin", "kd/pspbtdnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtjnf.bin", "kd/pspbtjnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtjnf_02g.bin", "kd/pspbtjnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtknf.bin", "kd/pspbtknf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtknf_02g.bin", "kd/pspbtknf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtlnf.bin", "kd/pspbtlnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtlnf_02g.bin", "kd/pspbtlnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC7/kd/resurrection.prx", "kd/resurrection.prx"},
	{"Magic Memory Stick/DC7/kd/systemctrl.prx", "kd/systemctrl.prx"},
	{"Magic Memory Stick/DC7/kd/systemctrl_02g.prx", "kd/systemctrl_02g.prx"},
	{"Magic Memory Stick/DC7/kd/usbdevice.prx", "kd/usbdevice.prx"},
	{"Magic Memory Stick/DC7/kd/vshctrl.prx", "kd/vshctrl.prx"},
	{"Magic Memory Stick/DC7/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DC7/vsh/module/recovery.prx", "vsh/module/recovery.prx"},
	{"Magic Memory Stick/DC7/vsh/module/satelite.prx", "vsh/module/satelite.prx"},
	{"Magic Memory Stick/DC7/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DC7/vsh/resource/bg.bmp", "vsh/resource/bg.bmp"}
};
struct DC8files {
	char	*inname;
	char	*outname;
} DC8files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC8/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC8/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DC8/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DC8/tmctrl500.prx", "tmctrl500.prx"},
	{"Magic Memory Stick/DC8/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DC8/kd/galaxy.prx", "kd/galaxy.prx"},
	{"Magic Memory Stick/DC8/kd/idcanager.prx", "kd/idcanager.prx"},
	{"Magic Memory Stick/DC8/kd/idsregeneration.prx", "kd/idsregeneration.prx"},
	{"Magic Memory Stick/DC8/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DC8/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DC8/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DC8/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC8/kd/march33.prx", "kd/march33.prx"},
	{"Magic Memory Stick/DC8/kd/popcorn.prx", "kd/popcorn.prx"},
	{"Magic Memory Stick/DC8/kd/pspbtdnf.bin", "kd/pspbtdnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtdnf_02g.bin", "kd/pspbtdnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtjnf.bin", "kd/pspbtjnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtjnf_02g.bin", "kd/pspbtjnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtknf.bin", "kd/pspbtknf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtknf_02g.bin", "kd/pspbtknf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtlnf.bin", "kd/pspbtlnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtlnf_02g.bin", "kd/pspbtlnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC8/kd/resurrection.prx", "kd/resurrection.prx"},
	{"Magic Memory Stick/DC8/kd/systemctrl.prx", "kd/systemctrl.prx"},
	{"Magic Memory Stick/DC8/kd/systemctrl_02g.prx", "kd/systemctrl_02g.prx"},
	{"Magic Memory Stick/DC8/kd/usbdevice.prx", "kd/usbdevice.prx"},
	{"Magic Memory Stick/DC8/kd/vshctrl.prx", "kd/vshctrl.prx"},
	{"Magic Memory Stick/DC8/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DC8/vsh/module/recovery.prx", "vsh/module/recovery.prx"},
	{"Magic Memory Stick/DC8/vsh/module/satelite.prx", "vsh/module/satelite.prx"},
	{"Magic Memory Stick/DC8/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DC8/vsh/resource/bg.bmp", "vsh/resource/bg.bmp"}
};
char *UpdateFlasherFiles[] = {
	"flash0:/kd/clockgen.prx",
	"flash0:/kd/ctrl.prx",
	"flash0:/kd/display.prx",
	"flash0:/kd/dmacman.prx",
	"flash0:/kd/dmacplus.prx",
	"flash0:/kd/emc_ddr.prx",
	"flash0:/kd/emc_sm.prx",
	"flash0:/kd/exceptionman.prx",
	"flash0:/kd/fatmsmod.prx",
	"flash0:/kd/ge.prx",
	"flash0:/kd/gpio.prx",
	"flash0:/kd/hpremote.prx",
	"flash0:/kd/i2c.prx",
	"flash0:/kd/idstorage.prx",
	"flash0:/kd/init.prx",
	"flash0:/kd/interruptman.prx",
	"flash0:/kd/iofilemgr.prx",
	"flash0:/kd/lcdc.prx",
	"flash0:/kd/led.prx",
	"flash0:/kd/lfatfs.prx",
	"flash0:/kd/loadcore.prx",
	"flash0:/kd/loadexec.prx",
	"flash0:/kd/memab.prx",
	"flash0:/kd/memlmd.prx",
	"flash0:/kd/mesg_led.prx",
	"flash0:/kd/modulemgr.prx",
	"flash0:/kd/mscm.prx",
	"flash0:/kd/msstor.prx",
	"flash0:/kd/power.prx",
	"flash0:/kd/pspnet_resolver.prx",
	"flash0:/kd/pwm.prx",
	"flash0:/kd/registry.prx",
	"flash0:/kd/rtc.prx",
	"flash0:/kd/stdio.prx",
	"flash0:/kd/sysclib.prx",
	"flash0:/kd/syscon.prx",
	"flash0:/kd/sysmem.prx",
	"flash0:/kd/sysreg.prx",
	"flash0:/kd/systimer.prx",
	"flash0:/kd/threadman.prx",
	"flash0:/kd/usersystemlib.prx",
	"flash0:/kd/utils.prx",
	"flash0:/kd/pspcnf_tbl.txt",
	"0"
};
char *DC_150Files[] = {
	"flash0:/kd/exceptionman.prx",
	"flash0:/kd/fatmsmod.prx",
	"flash0:/kd/ge.prx",
	"flash0:/kd/hpremote.prx",
	"flash0:/kd/idstorage.prx",
	"flash0:/kd/init.prx",
	"flash0:/kd/interruptman.prx",
	"flash0:/kd/iofilemgr.prx",
	"flash0:/kd/lfatfs.prx",
	"flash0:/kd/loadcore.prx",
	"flash0:/kd/loadexec.prx",
	"flash0:/kd/memab.prx",
	"flash0:/kd/memlmd.prx",
	"flash0:/kd/mesg_led.prx",
	"flash0:/kd/modulemgr.prx",
	"flash0:/kd/mscm.prx",
	"flash0:/kd/msstor.prx",
	"flash0:/kd/pspcnf_tbl.txt",
	"flash0:/kd/pspnet_resolver.prx",
	"flash0:/kd/registry.prx",
	"flash0:/kd/rtc.prx",
	"flash0:/kd/stdio.prx",
	"flash0:/kd/sysclib.prx",
	"flash0:/kd/sysmem.prx",
	"flash0:/kd/threadman.prx",
	"flash0:/kd/usersystemlib.prx",
	"flash0:/kd/utils.prx",
	"0"
};
char *DC_340Files[] = {
	"flash0:/kd/clockgen.prx",
	"flash0:/kd/ctrl.prx",
	"flash0:/kd/display.prx",
	"flash0:/kd/dmacman.prx",
	"flash0:/kd/dmacplus.prx",
	"flash0:/kd/emc_ddr.prx",
	"flash0:/kd/emc_sm.prx",
	"flash0:/kd/gpio.prx",
	"flash0:/kd/i2c.prx",
	"flash0:/kd/lcdc.prx",
	"flash0:/kd/led.prx",
	"flash0:/kd/power.prx",
	"flash0:/kd/pwm.prx",
	"flash0:/kd/syscon.prx",
	"flash0:/kd/sysreg.prx",
	"flash0:/kd/systimer.prx",
	"0"
};