struct UpdateFlasher150files {
	char	*inname;
	char	*outname;
} UpdateFlasher150files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/1.50 Update Flasher/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/extprxs.elf", "kd/extprxs.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/restore.elf", "kd/restore.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/updateflasher.elf", "kd/updateflasher.elf"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/decryptprx.prx", "kd/decryptprx.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/ta082_driver.prx", "kd/ta082_driver.prx"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/1.50 Update Flasher/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"}
};
struct DC3files {
	char	*inname;
	char	*outname;
} DC3files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC3/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/DC3/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC3/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC3/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC3/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC3/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC3/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC3/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC3/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC4files {
	char	*inname;
	char	*outname;
} DC4files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC4/ipl.bin", "TM/pandora.bin"},
	{"Magic Memory Stick/DC4/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC4/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC4/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC4/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC4/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC4/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC4/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC4/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC5files {
	char	*inname;
	char	*outname;
} DC5files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC5/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC5/kd/backup.elf", "kd/backup.elf"},
	{"Magic Memory Stick/DC5/kd/flashemu.prx", "kd/flashemu.prx"},
	{"Magic Memory Stick/DC5/kd/hibari.prx", "kd/hibari.prx"},
	{"Magic Memory Stick/DC5/kd/lfatfs_patched.prx", "kd/lfatfs_patched.prx"},
	{"Magic Memory Stick/DC5/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf.txt", "kd/pspbtcnf.txt"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf_game.txt", "kd/pspbtcnf_game.txt"},
	{"Magic Memory Stick/DC5/kd/pspbtcnf_updater.txt", "kd/pspbtcnf_updater.txt"},
	{"Magic Memory Stick/DC5/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC5/kd/resurrection.elf", "kd/resurrection.elf"}
};
struct DC7files {
	char	*inname;
	char	*outname;
} DC7files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC7/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC7/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DC7/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DC7/tmctrl401.prx", "tmctrl401.prx"},
	{"Magic Memory Stick/DC7/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DC7/kd/galaxy.prx", "kd/galaxy.prx"},
	{"Magic Memory Stick/DC7/kd/idcanager.prx", "kd/idcanager.prx"},
	{"Magic Memory Stick/DC7/kd/idsregeneration.prx", "kd/idsregeneration.prx"},
	{"Magic Memory Stick/DC7/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DC7/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DC7/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DC7/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC7/kd/march33.prx", "kd/march33.prx"},
	{"Magic Memory Stick/DC7/kd/popcorn.prx", "kd/popcorn.prx"},
	{"Magic Memory Stick/DC7/kd/pspbtdnf.bin", "kd/pspbtdnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtdnf_02g.bin", "kd/pspbtdnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtjnf.bin", "kd/pspbtjnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtjnf_02g.bin", "kd/pspbtjnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtknf.bin", "kd/pspbtknf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtknf_02g.bin", "kd/pspbtknf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtlnf.bin", "kd/pspbtlnf.bin"},
	{"Magic Memory Stick/DC7/kd/pspbtlnf_02g.bin", "kd/pspbtlnf_02g.bin"},
	{"Magic Memory Stick/DC7/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC7/kd/resurrection.prx", "kd/resurrection.prx"},
	{"Magic Memory Stick/DC7/kd/systemctrl.prx", "kd/systemctrl.prx"},
	{"Magic Memory Stick/DC7/kd/systemctrl_02g.prx", "kd/systemctrl_02g.prx"},
	{"Magic Memory Stick/DC7/kd/usbdevice.prx", "kd/usbdevice.prx"},
	{"Magic Memory Stick/DC7/kd/vshctrl.prx", "kd/vshctrl.prx"},
	{"Magic Memory Stick/DC7/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DC7/vsh/module/recovery.prx", "vsh/module/recovery.prx"},
	{"Magic Memory Stick/DC7/vsh/module/satelite.prx", "vsh/module/satelite.prx"},
	{"Magic Memory Stick/DC7/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DC7/vsh/resource/bg.bmp", "vsh/resource/bg.bmp"}
};

struct DC10files {
	char	*inname;
	char	*outname;
} DC10files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DCARK/msipl_11g.bin", "msipl_11g.bin"},
	{"Magic Memory Stick/DCARK/payload_02g.bin", "payload_02g.bin"},
	{"Magic Memory Stick/DCARK/msipl_02g.bin", "msipl_02g.bin"},
	{"Magic Memory Stick/DCARK/cipl_07g.bin", "cipl_07g.bin"},
	{"Magic Memory Stick/DCARK/cipl_09g.bin", "cipl_09g.bin"},
	{"Magic Memory Stick/DCARK/tmctrl.prx", "tmctrl.prx"},
	{"Magic Memory Stick/DCARK/cipl_02g.bin", "cipl_02g.bin"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_03g_dc.bin", "kd/pspbtcnf_03g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DCARK/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_dc.bin", "kd/pspbtcnf_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_07g_dc.bin", "kd/pspbtcnf_07g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_11g_dc.bin", "kd/pspbtcnf_11g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/ark_pspcompat.prx", "kd/ark_pspcompat.prx"},
	{"Magic Memory Stick/DCARK/kd/ark_popcorn.prx", "kd/ark_popcorn.prx"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_05g_dc.bin", "kd/pspbtcnf_05g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_02g_dc.bin", "kd/pspbtcnf_02g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/lfatfs_updater.prx", "kd/lfatfs_updater.prx"},
	{"Magic Memory Stick/DCARK/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DCARK/kd/ark_systemctrl.prx", "kd/ark_systemctrl.prx"},
	{"Magic Memory Stick/DCARK/kd/ark_inferno.prx", "kd/ark_inferno.prx"},
	{"Magic Memory Stick/DCARK/kd/lflash_fatfmt_updater.prx", "kd/lflash_fatfmt_updater.prx"},
	{"Magic Memory Stick/DCARK/kd/ark_stargate.prx", "kd/ark_stargate.prx"},
	{"Magic Memory Stick/DCARK/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_09g_dc.bin", "kd/pspbtcnf_09g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/emc_sm_updater.prx", "kd/emc_sm_updater.prx"},
	{"Magic Memory Stick/DCARK/kd/pspbtcnf_04g_dc.bin", "kd/pspbtcnf_04g_dc.bin"},
	{"Magic Memory Stick/DCARK/kd/ark_vshctrl.prx", "kd/ark_vshctrl.prx"},
	{"Magic Memory Stick/DCARK/ARK_01234", "ARK_01234"},
	{"Magic Memory Stick/DCARK/ARK_01234/RECOVERY.PRX", "ARK_01234/RECOVERY.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/MEDIASYN.PRX", "ARK_01234/MEDIASYN.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/H.BIN", "ARK_01234/H.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/VBOOT.PBP", "ARK_01234/VBOOT.PBP"},
	{"Magic Memory Stick/DCARK/ARK_01234/VSHMENU.PRX", "ARK_01234/VSHMENU.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/THEME.ARK", "ARK_01234/THEME.ARK"},
	{"Magic Memory Stick/DCARK/ARK_01234/USBDEV.PRX", "ARK_01234/USBDEV.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/ICON0.PNG", "ARK_01234/ICON0.PNG"},
	{"Magic Memory Stick/DCARK/ARK_01234/SETTINGS.TXT", "ARK_01234/SETTINGS.TXT"},
	{"Magic Memory Stick/DCARK/ARK_01234/ARK4.BIN", "ARK_01234/ARK4.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/K.BIN", "ARK_01234/K.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/POPSMAN.PRX", "ARK_01234/POPSMAN.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/PS1SPU.PRX", "ARK_01234/PS1SPU.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/ARKX.BIN", "ARK_01234/ARKX.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/SAVEDATA.BIN", "ARK_01234/SAVEDATA.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/XMBCTRL.PRX", "ARK_01234/XMBCTRL.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/ARK.BIN", "ARK_01234/ARK.BIN"},
	{"Magic Memory Stick/DCARK/ARK_01234/POPS.PRX", "ARK_01234/POPS.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/LANG.ARK", "ARK_01234/LANG.ARK"},
	{"Magic Memory Stick/DCARK/ARK_01234/XBOOT.PBP", "ARK_01234/XBOOT.PBP"},
	{"Magic Memory Stick/DCARK/ARK_01234/UPDATER.TXT", "ARK_01234/UPDATER.TXT"},
	{"Magic Memory Stick/DCARK/ARK_01234/FLASH0.ARK", "ARK_01234/FLASH0.ARK"},
	{"Magic Memory Stick/DCARK/ARK_01234/IDSREG.PRX", "ARK_01234/IDSREG.PRX"},
	{"Magic Memory Stick/DCARK/ARK_01234/PARAM.SFO", "ARK_01234/PARAM.SFO"},
	{"Magic Memory Stick/DCARK/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DCARK/ipl_09g.bin", "ipl_09g.bin"},
	{"Magic Memory Stick/DCARK/msipl_09g.bin", "msipl_09g.bin"},
	{"Magic Memory Stick/DCARK/ipl_04g.bin", "ipl_04g.bin"},
	{"Magic Memory Stick/DCARK/ipl_07g.bin", "ipl_07g.bin"},
	{"Magic Memory Stick/DCARK/cipl_05g.bin", "cipl_05g.bin"},
	{"Magic Memory Stick/DCARK/cipl_11g.bin", "cipl_11g.bin"},
	{"Magic Memory Stick/DCARK/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DCARK/cipl_03g.bin", "cipl_03g.bin"},
	{"Magic Memory Stick/DCARK/msipl_05g.bin", "msipl_05g.bin"},
	{"Magic Memory Stick/DCARK/nandipl_02g.bin", "nandipl_02g.bin"},
	{"Magic Memory Stick/DCARK/msipl.bin", "msipl.bin"},
	{"Magic Memory Stick/DCARK/msipl.raw", "msipl.raw"},
	{"Magic Memory Stick/DCARK/ipl_11g.bin", "ipl_11g.bin"},
	{"Magic Memory Stick/DCARK/nandipl_01g.bin", "nandipl_01g.bin"},
	{"Magic Memory Stick/DCARK/msipl_07g.bin", "msipl_07g.bin"},
	{"Magic Memory Stick/DCARK/vsh", "vsh"},
	{"Magic Memory Stick/DCARK/vsh/module", "vsh/module"},
	{"Magic Memory Stick/DCARK/vsh/module/resurrection.prx", "vsh/module/resurrection.prx"},
	{"Magic Memory Stick/DCARK/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DCARK/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DCARK/msipl_04g.bin", "msipl_04g.bin"},
	{"Magic Memory Stick/DCARK/cipl_04g.bin", "cipl_04g.bin"},
	{"Magic Memory Stick/DCARK/cipl_01g.bin", "cipl_01g.bin"},
	{"Magic Memory Stick/DCARK/msipl_03g.bin", "msipl_03g.bin"},
	{"Magic Memory Stick/DCARK/ipl_05g.bin", "ipl_05g.bin"},
	{"Magic Memory Stick/DCARK/msipl_01g.bin", "msipl_01g.bin"},
	{"Magic Memory Stick/DCARK/ipl_03g.bin", "ipl_03g.bin"},
	{"Magic Memory Stick/DCARK/tm_mloader.bin", "tm_mloader.bin"},
	{"Magic Memory Stick/DCARK/payload_01g.bin", "payload_01g.bin"},

};
struct DC8files {
	char	*inname;
	char	*outname;
} DC8files[] = {
	{"System/registry/system.dreg", "registry/system.dreg"},
	{"System/registry/system.ireg", "registry/system.ireg"},
	{"Magic Memory Stick/DC8/ipl.bin", "ipl.bin"},
	{"Magic Memory Stick/DC8/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DC8/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DC8/tmctrl500.prx", "tmctrl500.prx"},
	{"Magic Memory Stick/DC8/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DC8/kd/galaxy.prx", "kd/galaxy.prx"},
	{"Magic Memory Stick/DC8/kd/idcanager.prx", "kd/idcanager.prx"},
	{"Magic Memory Stick/DC8/kd/idsregeneration.prx", "kd/idsregeneration.prx"},
	{"Magic Memory Stick/DC8/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DC8/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DC8/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DC8/kd/libpsardumper.prx", "kd/libpsardumper.prx"},
	{"Magic Memory Stick/DC8/kd/march33.prx", "kd/march33.prx"},
	{"Magic Memory Stick/DC8/kd/popcorn.prx", "kd/popcorn.prx"},
	{"Magic Memory Stick/DC8/kd/pspbtdnf.bin", "kd/pspbtdnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtdnf_02g.bin", "kd/pspbtdnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtjnf.bin", "kd/pspbtjnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtjnf_02g.bin", "kd/pspbtjnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtknf.bin", "kd/pspbtknf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtknf_02g.bin", "kd/pspbtknf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtlnf.bin", "kd/pspbtlnf.bin"},
	{"Magic Memory Stick/DC8/kd/pspbtlnf_02g.bin", "kd/pspbtlnf_02g.bin"},
	{"Magic Memory Stick/DC8/kd/pspdecrypt.prx", "kd/pspdecrypt.prx"},
	{"Magic Memory Stick/DC8/kd/resurrection.prx", "kd/resurrection.prx"},
	{"Magic Memory Stick/DC8/kd/systemctrl.prx", "kd/systemctrl.prx"},
	{"Magic Memory Stick/DC8/kd/systemctrl_02g.prx", "kd/systemctrl_02g.prx"},
	{"Magic Memory Stick/DC8/kd/usbdevice.prx", "kd/usbdevice.prx"},
	{"Magic Memory Stick/DC8/kd/vshctrl.prx", "kd/vshctrl.prx"},
	{"Magic Memory Stick/DC8/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DC8/vsh/module/recovery.prx", "vsh/module/recovery.prx"},
	{"Magic Memory Stick/DC8/vsh/module/satelite.prx", "vsh/module/satelite.prx"},
	{"Magic Memory Stick/DC8/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DC8/vsh/resource/bg.bmp", "vsh/resource/bg.bmp"}
};
struct DC9files {
	char	*inname;
	char	*outname;
} DC9files[] = {
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_03g_m33.bin", "testingtool/kd/pspbtcnf_03g_m33.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/endora.prx", "testingtool/kd/endora.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_03g_dc.bin", "testingtool/kd/pspbtcnf_03g_dc.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_dc.bin", "testingtool/kd/pspbtcnf_dc.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_02g_umd.bin", "testingtool/kd/pspbtcnf_02g_umd.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_umd.bin", "testingtool/kd/pspbtcnf_umd.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/rtcinit.prx", "testingtool/kd/rtcinit.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_np.bin", "testingtool/kd/pspbtcnf_np.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/uart4.prx", "testingtool/kd/uart4.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_03g_umd.bin", "testingtool/kd/pspbtcnf_03g_umd.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/usbdmb_tool.prx", "testingtool/kd/usbdmb_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/np9660_tool.prx", "testingtool/kd/np9660_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_02g_np.bin", "testingtool/kd/pspbtcnf_02g_np.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/vshbridge_tool.prx", "testingtool/kd/vshbridge_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/crashdump.prx", "testingtool/kd/crashdump.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_03g_recovery.bin", "testingtool/kd/pspbtcnf_03g_recovery.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_02g_recovery.bin", "testingtool/kd/pspbtcnf_02g_recovery.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/umdcache_tool.prx", "testingtool/kd/umdcache_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_02g_dc.bin", "testingtool/kd/pspbtcnf_02g_dc.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/idmanager_tool.prx", "testingtool/kd/idmanager_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/bsod.prx", "testingtool/kd/bsod.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_03g_np.bin", "testingtool/kd/pspbtcnf_03g_np.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_recovery.bin", "testingtool/kd/pspbtcnf_recovery.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_02g_m33.bin", "testingtool/kd/pspbtcnf_02g_m33.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/usbgps_serial.prx", "testingtool/kd/usbgps_serial.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/pspbtcnf_m33.bin", "testingtool/kd/pspbtcnf_m33.bin"},
	{"Magic Memory Stick/DC9/testingtool/kd/sm1.prx", "testingtool/kd/sm1.prx"},
	{"Magic Memory Stick/DC9/testingtool/kd/npdrm_tool.prx", "testingtool/kd/npdrm_tool.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_browser.prx", "testingtool/vsh/module/rss_browser.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netfront.prx", "testingtool/vsh/module/netfront.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/photo_player.prx", "testingtool/vsh/module/photo_player.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/launcher_plugin.prx", "testingtool/vsh/module/launcher_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/dd_helper_utility.prx", "testingtool/vsh/module/dd_helper_utility.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/content_browser.prx", "testingtool/vsh/module/content_browser.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/store_checkout_plugin.prx", "testingtool/vsh/module/store_checkout_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_subscriber.prx", "testingtool/vsh/module/rss_subscriber.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/ps3scan_plugin.prx", "testingtool/vsh/module/ps3scan_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/npsignin_plugin.prx", "testingtool/vsh/module/npsignin_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/htmlviewer_ui.prx", "testingtool/vsh/module/htmlviewer_ui.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/hvauth_t.prx", "testingtool/vsh/module/hvauth_t.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/screenshot_plugin.prx", "testingtool/vsh/module/screenshot_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_main_plugin.prx", "testingtool/vsh/module/rss_main_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/psn_plugin.prx", "testingtool/vsh/module/psn_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/mm_flash.prx", "testingtool/vsh/module/mm_flash.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/file_parser_base.prx", "testingtool/vsh/module/file_parser_base.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/osk_plugin.prx", "testingtool/vsh/module/osk_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/dd_helper.prx", "testingtool/vsh/module/dd_helper.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_common.prx", "testingtool/vsh/module/rss_common.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/vshmain.prx", "testingtool/vsh/module/vshmain.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/htmlviewer_utility.prx", "testingtool/vsh/module/htmlviewer_utility.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netplay_client_plugin.prx", "testingtool/vsh/module/netplay_client_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/libslim.prx", "testingtool/vsh/module/libslim.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/sysconf_plugin.prx", "testingtool/vsh/module/sysconf_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/savedata_utility.prx", "testingtool/vsh/module/savedata_utility.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/npsignup_plugin.prx", "testingtool/vsh/module/npsignup_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/npinstaller_plugin.prx", "testingtool/vsh/module/npinstaller_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/store_browser_plugin.prx", "testingtool/vsh/module/store_browser_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netplay_server_plus_utility.prx", "testingtool/vsh/module/netplay_server_plus_utility.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netconf_plugin_auto_nec.prx", "testingtool/vsh/module/netconf_plugin_auto_nec.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/premo_plugin.prx", "testingtool/vsh/module/premo_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_downloader.prx", "testingtool/vsh/module/rss_downloader.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/dialogmain.prx", "testingtool/vsh/module/dialogmain.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/game_plugin.prx", "testingtool/vsh/module/game_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/npadmin_plugin.prx", "testingtool/vsh/module/npadmin_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/adhoc_transfer.prx", "testingtool/vsh/module/adhoc_transfer.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/impose_plugin.prx", "testingtool/vsh/module/impose_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/photo_browser.prx", "testingtool/vsh/module/photo_browser.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netconf_plugin.prx", "testingtool/vsh/module/netconf_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/savedata_auto_dialog.prx", "testingtool/vsh/module/savedata_auto_dialog.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/libfont_hv.prx", "testingtool/vsh/module/libfont_hv.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/pafmini.prx", "testingtool/vsh/module/pafmini.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netconf_plugin_auto_bfl.prx", "testingtool/vsh/module/netconf_plugin_auto_bfl.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/photo_main_plugin.prx", "testingtool/vsh/module/photo_main_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/dnas_plugin.prx", "testingtool/vsh/module/dnas_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/savedata_plugin.prx", "testingtool/vsh/module/savedata_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/paf.prx", "testingtool/vsh/module/paf.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/opening_plugin.prx", "testingtool/vsh/module/opening_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/libwww.prx", "testingtool/vsh/module/libwww.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/msgdialog_plugin.prx", "testingtool/vsh/module/msgdialog_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/htmlviewer_plugin.prx", "testingtool/vsh/module/htmlviewer_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/auth_plugin.prx", "testingtool/vsh/module/auth_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/common_gui.prx", "testingtool/vsh/module/common_gui.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/game_install_plugin.prx", "testingtool/vsh/module/game_install_plugin.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/rss_reader.prx", "testingtool/vsh/module/rss_reader.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/common_util.prx", "testingtool/vsh/module/common_util.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/module/netplay_server_utility.prx", "testingtool/vsh/module/netplay_server_utility.prx"},
	{"Magic Memory Stick/DC9/testingtool/vsh/etc/index_02g.dat", "testingtool/vsh/etc/index_02g.dat"},
	{"Magic Memory Stick/DC9/testingtool/vsh/etc/index_01g.dat", "testingtool/vsh/etc/index_01g.dat"},
	{"Magic Memory Stick/DC9/testingtool/vsh/etc/index_03g.dat", "testingtool/vsh/etc/index_03g.dat"},
	{"Magic Memory Stick/DC9/testingtool/vsh/etc/cptbl.dat", "testingtool/vsh/etc/cptbl.dat"},
	{"Magic Memory Stick/DC9/testingtool/vsh/etc/version.txt", "testingtool/vsh/etc/version.txt"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/npsignup_plugin.rco", "testingtool/vsh/resource/npsignup_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/13-27.bmp", "testingtool/vsh/resource/13-27.bmp"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/screenshot_plugin.rco", "testingtool/vsh/resource/screenshot_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/rss_downloader_plugin.rco", "testingtool/vsh/resource/rss_downloader_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/game_plugin.rco", "testingtool/vsh/resource/game_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/ps3scan_plugin.rco", "testingtool/vsh/resource/ps3scan_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/common_page.rco", "testingtool/vsh/resource/common_page.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/msgdialog_plugin.rco", "testingtool/vsh/resource/msgdialog_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/store_browser_plugin.rco", "testingtool/vsh/resource/store_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/dd_helper.rco", "testingtool/vsh/resource/dd_helper.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/system_plugin_fg.rco", "testingtool/vsh/resource/system_plugin_fg.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/netconf_dialog.rco", "testingtool/vsh/resource/netconf_dialog.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/savedata_plugin.rco", "testingtool/vsh/resource/savedata_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/store_checkout_plugin.rco", "testingtool/vsh/resource/store_checkout_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/netplay_plugin.rco", "testingtool/vsh/resource/netplay_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/npsignin_plugin.rco", "testingtool/vsh/resource/npsignin_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/topmenu_icon.rco", "testingtool/vsh/resource/topmenu_icon.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/sysconf_plugin_about.rco", "testingtool/vsh/resource/sysconf_plugin_about.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/npadmin_plugin.rco", "testingtool/vsh/resource/npadmin_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/premo_plugin.rco", "testingtool/vsh/resource/premo_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/npinstaller_plugin.rco", "testingtool/vsh/resource/npinstaller_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/gameboot.pmf", "testingtool/vsh/resource/gameboot.pmf"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/auth_plugin.rco", "testingtool/vsh/resource/auth_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/photo_browser_plugin.rco", "testingtool/vsh/resource/photo_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/01-12.bmp", "testingtool/vsh/resource/01-12.bmp"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/content_browser_plugin.rco", "testingtool/vsh/resource/content_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/topmenu_plugin.rco", "testingtool/vsh/resource/topmenu_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/osk_plugin.rco", "testingtool/vsh/resource/osk_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/photo_player_plugin.rco", "testingtool/vsh/resource/photo_player_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/opening_plugin.rco", "testingtool/vsh/resource/opening_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/sysconf_plugin.rco", "testingtool/vsh/resource/sysconf_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/01-12_03g.bmp", "testingtool/vsh/resource/01-12_03g.bmp"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/rss_browser_plugin.rco", "testingtool/vsh/resource/rss_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/system_plugin.rco", "testingtool/vsh/resource/system_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/dnas_plugin.rco", "testingtool/vsh/resource/dnas_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/htmlviewer.res", "testingtool/vsh/resource/htmlviewer.res"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/system_plugin_bg.rco", "testingtool/vsh/resource/system_plugin_bg.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/htmlviewer_plugin.rco", "testingtool/vsh/resource/htmlviewer_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/osk_utility.rco", "testingtool/vsh/resource/osk_utility.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/savedata_utility.rco", "testingtool/vsh/resource/savedata_utility.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/game_install_plugin.rco", "testingtool/vsh/resource/game_install_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/adhoc_transfer.rco", "testingtool/vsh/resource/adhoc_transfer.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/impose_plugin.rco", "testingtool/vsh/resource/impose_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/psn_plugin.rco", "testingtool/vsh/resource/psn_plugin.rco"},
	{"Magic Memory Stick/DC9/testingtool/vsh/resource/rss_subscriber.rco", "testingtool/vsh/resource/rss_subscriber.rco"},
	{"Magic Memory Stick/DC9/tmctrl.prx", "tmctrl.prx"},
	{"Magic Memory Stick/DC9/kd/resurrection.prx", "kd/resurrection.prx"},
	{"Magic Memory Stick/DC9/kd/lflash_fdisk.prx", "kd/lflash_fdisk.prx"},
	{"Magic Memory Stick/DC9/kd/dcman.prx", "kd/dcman.prx"},
	{"Magic Memory Stick/DC9/kd/galaxy.prx", "kd/galaxy.prx"},
	{"Magic Memory Stick/DC9/kd/idcanager.prx", "kd/idcanager.prx"},
	{"Magic Memory Stick/DC9/kd/idsregeneration.prx", "kd/idsregeneration.prx"},
	{"Magic Memory Stick/DC9/kd/march33.prx", "kd/march33.prx"},
	{"Magic Memory Stick/DC9/kd/iop.prx", "kd/iop.prx"},
	{"Magic Memory Stick/DC9/kd/ipl_update.prx", "kd/ipl_update.prx"},
	{"Magic Memory Stick/DC9/kd/systemctrl.prx", "kd/systemctrl.prx"},
	{"Magic Memory Stick/DC9/kd/systemctrl_02g.prx", "kd/systemctrl_02g.prx"},
	{"Magic Memory Stick/DC9/kd/systemctrl_03g.prx", "kd/systemctrl_03g.prx"},
	{"Magic Memory Stick/DC9/kd/vshctrl.prx", "kd/vshctrl.prx"},
	{"Magic Memory Stick/DC9/ipl_01g.bin", "ipl_01g.bin"},
	{"Magic Memory Stick/DC9/nandcipl_03g.bin", "nandcipl_03g.bin"},
	{"Magic Memory Stick/DC9/ipl_02g.bin", "ipl_02g.bin"},
	{"Magic Memory Stick/DC9/nandipl_02g.bin", "nandipl_02g.bin"},
	{"Magic Memory Stick/DC9/nandipl_02g.bin", "nandipl_02g.bin"},
	{"Magic Memory Stick/DC9/nandipl_03g.bin", "nandipl_03g.bin"},
	{"Magic Memory Stick/DC9/nandipl_01g.bin", "nandipl_01g.bin"},
	{"Magic Memory Stick/DC9/vsh/module/satelite.prx", "vsh/module/satelite.prx"},
	{"Magic Memory Stick/DC9/vsh/module/vlf.prx", "vsh/module/vlf.prx"},
	{"Magic Memory Stick/DC9/vsh/module/recovery.prx", "vsh/module/recovery.prx"},
	{"Magic Memory Stick/DC9/vsh/module/intraFont.prx", "vsh/module/intraFont.prx"},
	{"Magic Memory Stick/DC9/nandcipl_01g.bin", "nandcipl_01g.bin"},
	{"Magic Memory Stick/DC9/nandcipl_02g.bin", "nandcipl_02g.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g_m33.bin", "retail/kd/pspbtcnf_03g_m33.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g_dc.bin", "retail/kd/pspbtcnf_03g_dc.bin"}, 
	{"Magic Memory Stick/DC9/retail/kd/idmanager.prx", "retail/kd/idmanager.prx"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_dc.bin", "retail/kd/pspbtcnf_dc.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g_umd.bin", "retail/kd/pspbtcnf_02g_umd.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_umd.bin", "retail/kd/pspbtcnf_umd.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_np.bin", "retail/kd/pspbtcnf_np.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g_umd.bin", "retail/kd/pspbtcnf_03g_umd.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g_np.bin", "retail/kd/pspbtcnf_02g_np.bin"},
	{"Magic Memory Stick/DC9/retail/kd/vshbridge.prx", "retail/kd/vshbridge.prx"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g_recovery.bin", "retail/kd/pspbtcnf_03g_recovery.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g_recovery.bin", "retail/kd/pspbtcnf_02g_recovery.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g_dc.bin", "retail/kd/pspbtcnf_02g_dc.bin"},
	{"Magic Memory Stick/DC9/retail/kd/np9660.prx", "retail/kd/np9660.prx"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g.bin", "retail/kd/pspbtcnf_03g.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf.bin", "retail/kd/pspbtcnf.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_03g_np.bin", "retail/kd/pspbtcnf_03g_np.bin"},
	{"Magic Memory Stick/DC9/retail/kd/npdrm.prx", "retail/kd/npdrm.prx"},
	{"Magic Memory Stick/DC9/retail/kd/mgvideo.prx", "retail/kd/mgvideo.prx"},
	{"Magic Memory Stick/DC9/retail/kd/msaudio.prx", "retail/kd/msaudio.prx"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_recovery.bin", "retail/kd/pspbtcnf_recovery.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g_m33.bin", "retail/kd/pspbtcnf_02g_m33.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_m33.bin", "retail/kd/pspbtcnf_m33.bin"},
	{"Magic Memory Stick/DC9/retail/kd/pspbtcnf_02g.bin", "retail/kd/pspbtcnf_02g.bin"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_browser.prx", "retail/vsh/module/rss_browser.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netfront.prx", "retail/vsh/module/netfront.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/photo_player.prx", "retail/vsh/module/photo_player.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/launcher_plugin.prx", "retail/vsh/module/launcher_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/dd_helper_utility.prx", "retail/vsh/module/dd_helper_utility.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/content_browser.prx", "retail/vsh/module/content_browser.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/store_checkout_plugin.prx", "retail/vsh/module/store_checkout_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_subscriber.prx", "retail/vsh/module/rss_subscriber.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/ps3scan_plugin.prx", "retail/vsh/module/ps3scan_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/npsignin_plugin.prx", "retail/vsh/module/npsignin_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/htmlviewer_ui.prx", "retail/vsh/module/htmlviewer_ui.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/camera_plugin.prx", "retail/vsh/module/camera_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/screenshot_plugin.prx", "retail/vsh/module/screenshot_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_main_plugin.prx", "retail/vsh/module/rss_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/psn_plugin.prx", "retail/vsh/module/psn_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/mm_flash.prx", "retail/vsh/module/mm_flash.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/file_parser_base.prx", "retail/vsh/module/file_parser_base.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/osk_plugin.prx", "retail/vsh/module/osk_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/dd_helper.prx", "retail/vsh/module/dd_helper.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_common.prx", "retail/vsh/module/rss_common.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/vshmain.prx", "retail/vsh/module/vshmain.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/htmlviewer_utility.prx", "retail/vsh/module/htmlviewer_utility.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netplay_client_plugin.prx", "retail/vsh/module/netplay_client_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/osk_plugin_500.prx", "retail/vsh/module/osk_plugin_500.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_core.prx", "retail/vsh/module/oneseg_core.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/mlnusb.prx", "retail/vsh/module/mlnusb.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/libslim.prx", "retail/vsh/module/libslim.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/lftv_main_plugin.prx", "retail/vsh/module/lftv_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/sysconf_plugin.prx", "retail/vsh/module/sysconf_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/savedata_utility.prx", "retail/vsh/module/savedata_utility.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/npsignup_plugin.prx", "retail/vsh/module/npsignup_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_sal.prx", "retail/vsh/module/oneseg_sal.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/npinstaller_plugin.prx", "retail/vsh/module/npinstaller_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/store_browser_plugin.prx", "retail/vsh/module/store_browser_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netplay_server_plus_utility.prx", "retail/vsh/module/netplay_server_plus_utility.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/msvideo_plugin.prx", "retail/vsh/module/msvideo_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/lftv_plugin.prx", "retail/vsh/module/lftv_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netconf_plugin_auto_nec.prx", "retail/vsh/module/netconf_plugin_auto_nec.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/msvideo_main_plugin.prx", "retail/vsh/module/msvideo_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/premo_plugin.prx", "retail/vsh/module/premo_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_downloader.prx", "retail/vsh/module/rss_downloader.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/music_main_plugin.prx", "retail/vsh/module/music_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/mcore.prx", "retail/vsh/module/mcore.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/dialogmain.prx", "retail/vsh/module/dialogmain.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/game_plugin.prx", "retail/vsh/module/game_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/npadmin_plugin.prx", "retail/vsh/module/npadmin_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/video_main_plugin.prx", "retail/vsh/module/video_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/adhoc_transfer.prx", "retail/vsh/module/adhoc_transfer.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/impose_plugin.prx", "retail/vsh/module/impose_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_launcher_plugin.prx", "retail/vsh/module/oneseg_launcher_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/music_player.prx", "retail/vsh/module/music_player.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/skype_plugin.prx", "retail/vsh/module/skype_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_hal_toolbox.prx", "retail/vsh/module/oneseg_hal_toolbox.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/photo_browser.prx", "retail/vsh/module/photo_browser.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/music_parser.prx", "retail/vsh/module/music_parser.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netconf_plugin.prx", "retail/vsh/module/netconf_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/video_plugin.prx", "retail/vsh/module/video_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/savedata_auto_dialog.prx", "retail/vsh/module/savedata_auto_dialog.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/libfont_hv.prx", "retail/vsh/module/libfont_hv.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/visualizer_plugin.prx", "retail/vsh/module/visualizer_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_sdk.prx", "retail/vsh/module/oneseg_sdk.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/pafmini.prx", "retail/vsh/module/pafmini.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/libpspvmc.prx", "retail/vsh/module/libpspvmc.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/music_browser.prx", "retail/vsh/module/music_browser.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netconf_plugin_auto_bfl.prx", "retail/vsh/module/netconf_plugin_auto_bfl.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/photo_main_plugin.prx", "retail/vsh/module/photo_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/dnas_plugin.prx", "retail/vsh/module/dnas_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/savedata_plugin.prx", "retail/vsh/module/savedata_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/libfont_arib.prx", "retail/vsh/module/libfont_arib.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/paf.prx", "retail/vsh/module/paf.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/opening_plugin.prx", "retail/vsh/module/opening_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/libwww.prx", "retail/vsh/module/libwww.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/msgdialog_plugin.prx", "retail/vsh/module/msgdialog_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/htmlviewer_plugin.prx", "retail/vsh/module/htmlviewer_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/auth_plugin.prx", "retail/vsh/module/auth_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/skype_main_plugin.prx", "retail/vsh/module/skype_main_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/common_gui.prx", "retail/vsh/module/common_gui.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/skype_ve.prx", "retail/vsh/module/skype_ve.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/radioshack_plugin.prx", "retail/vsh/module/radioshack_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/game_install_plugin.prx", "retail/vsh/module/game_install_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_sdkcore.prx", "retail/vsh/module/oneseg_sdkcore.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/update_plugin.prx", "retail/vsh/module/update_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/rss_reader.prx", "retail/vsh/module/rss_reader.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/lftv_middleware.prx", "retail/vsh/module/lftv_middleware.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/skype_skyhost.prx", "retail/vsh/module/skype_skyhost.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/hvauth_r.prx", "retail/vsh/module/hvauth_r.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/oneseg_plugin.prx", "retail/vsh/module/oneseg_plugin.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/common_util.prx", "retail/vsh/module/common_util.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/module/netplay_server_utility.prx", "retail/vsh/module/netplay_server_utility.prx"},
	{"Magic Memory Stick/DC9/retail/vsh/etc/index_02g.dat", "retail/vsh/etc/index_02g.dat"},
	{"Magic Memory Stick/DC9/retail/vsh/etc/index_01g.dat", "retail/vsh/etc/index_01g.dat"},
	{"Magic Memory Stick/DC9/retail/vsh/etc/index_03g.dat", "retail/vsh/etc/index_03g.dat"},
	{"Magic Memory Stick/DC9/retail/vsh/etc/cptbl.dat", "retail/vsh/etc/cptbl.dat"},
	{"Magic Memory Stick/DC9/retail/vsh/etc/version.txt", "retail/vsh/etc/version.txt"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/video_plugin_videotoolbar.rco", "retail/vsh/resource/video_plugin_videotoolbar.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/npsignup_plugin.rco", "retail/vsh/resource/npsignup_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univer3in1.rco", "retail/vsh/resource/lftv_rmc_univer3in1.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/13-27.bmp", "retail/vsh/resource/13-27.bmp"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/screenshot_plugin.rco", "retail/vsh/resource/screenshot_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/rss_downloader_plugin.rco", "retail/vsh/resource/rss_downloader_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/game_plugin.rco", "retail/vsh/resource/game_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/oneseg_plugin.rco", "retail/vsh/resource/oneseg_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/ps3scan_plugin.rco", "retail/vsh/resource/ps3scan_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/common_page.rco", "retail/vsh/resource/common_page.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/music_player_plugin.rco", "retail/vsh/resource/music_player_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/video_main_plugin.rco", "retail/vsh/resource/video_main_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/msgdialog_plugin.rco", "retail/vsh/resource/msgdialog_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/store_browser_plugin.rco", "retail/vsh/resource/store_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/dd_helper.rco", "retail/vsh/resource/dd_helper.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/system_plugin_fg.rco", "retail/vsh/resource/system_plugin_fg.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/netconf_dialog.rco", "retail/vsh/resource/netconf_dialog.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univerpanel.rco", "retail/vsh/resource/lftv_rmc_univerpanel.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/osk_plugin_500.rco", "retail/vsh/resource/osk_plugin_500.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/savedata_plugin.rco", "retail/vsh/resource/savedata_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/store_checkout_plugin.rco", "retail/vsh/resource/store_checkout_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univer3in1_jp.rco", "retail/vsh/resource/lftv_rmc_univer3in1_jp.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/update_plugin.rco", "retail/vsh/resource/update_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/netplay_plugin.rco", "retail/vsh/resource/netplay_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/npsignin_plugin.rco", "retail/vsh/resource/npsignin_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_tuner_jp_jp.rco", "retail/vsh/resource/lftv_tuner_jp_jp.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/topmenu_icon.rco", "retail/vsh/resource/topmenu_icon.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/sysconf_plugin_about.rco", "retail/vsh/resource/sysconf_plugin_about.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/npadmin_plugin.rco", "retail/vsh/resource/npadmin_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/radioshack_plugin.rco", "retail/vsh/resource/radioshack_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/premo_plugin.rco", "retail/vsh/resource/premo_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/npinstaller_plugin.rco", "retail/vsh/resource/npinstaller_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/music_browser_plugin.rco", "retail/vsh/resource/music_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/custom_theme.dat", "retail/vsh/resource/custom_theme.dat"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/gameboot.pmf", "retail/vsh/resource/gameboot.pmf"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/visualizer_plugin.rco", "retail/vsh/resource/visualizer_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/auth_plugin.rco", "retail/vsh/resource/auth_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/photo_browser_plugin.rco", "retail/vsh/resource/photo_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/01-12.bmp", "retail/vsh/resource/01-12.bmp"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/content_browser_plugin.rco", "retail/vsh/resource/content_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/topmenu_plugin.rco", "retail/vsh/resource/topmenu_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/photo_player_plugin.rco", "retail/vsh/resource/photo_player_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/opening_plugin.rco", "retail/vsh/resource/opening_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/sysconf_plugin.rco", "retail/vsh/resource/sysconf_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/01-12_03g.bmp", "retail/vsh/resource/01-12_03g.bmp"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/rss_browser_plugin.rco", "retail/vsh/resource/rss_browser_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/system_plugin.rco", "retail/vsh/resource/system_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univertuner_jp.rco", "retail/vsh/resource/lftv_rmc_univertuner_jp.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/dnas_plugin.rco", "retail/vsh/resource/dnas_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/htmlviewer.res", "retail/vsh/resource/htmlviewer.res"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/system_plugin_bg.rco", "retail/vsh/resource/system_plugin_bg.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/htmlviewer_plugin.rco", "retail/vsh/resource/htmlviewer_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_tuner_us_en.rco", "retail/vsh/resource/lftv_tuner_us_en.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univerpanel_jp.rco", "retail/vsh/resource/lftv_rmc_univerpanel_jp.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/camera_plugin.rco", "retail/vsh/resource/camera_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/osk_utility.rco", "retail/vsh/resource/osk_utility.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/savedata_utility.rco", "retail/vsh/resource/savedata_utility.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_main_plugin.rco", "retail/vsh/resource/lftv_main_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/game_install_plugin.rco", "retail/vsh/resource/game_install_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/adhoc_transfer.rco", "retail/vsh/resource/adhoc_transfer.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/impose_plugin.rco", "retail/vsh/resource/impose_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/skype_main_plugin.rco", "retail/vsh/resource/skype_main_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/psn_plugin.rco", "retail/vsh/resource/psn_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/rss_subscriber.rco", "retail/vsh/resource/rss_subscriber.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/msvideo_main_plugin.rco", "retail/vsh/resource/msvideo_main_plugin.rco"},
	{"Magic Memory Stick/DC9/retail/vsh/resource/lftv_rmc_univertuner.rco", "retail/vsh/resource/lftv_rmc_univertuner.rco"},
	{"Magic Memory Stick/DC9/ipl_03g.bin", "ipl_03g.bin"},
};

char *UpdateFlasherFiles[] = {
	"flash0:/kd/clockgen.prx",
	"flash0:/kd/ctrl.prx",
	"flash0:/kd/display.prx",
	"flash0:/kd/dmacman.prx",
	"flash0:/kd/dmacplus.prx",
	"flash0:/kd/emc_ddr.prx",
	"flash0:/kd/emc_sm.prx",
	"flash0:/kd/exceptionman.prx",
	"flash0:/kd/fatmsmod.prx",
	"flash0:/kd/ge.prx",
	"flash0:/kd/gpio.prx",
	"flash0:/kd/hpremote.prx",
	"flash0:/kd/i2c.prx",
	"flash0:/kd/idstorage.prx",
	"flash0:/kd/init.prx",
	"flash0:/kd/interruptman.prx",
	"flash0:/kd/iofilemgr.prx",
	"flash0:/kd/lcdc.prx",
	"flash0:/kd/led.prx",
	"flash0:/kd/lfatfs.prx",
	"flash0:/kd/loadcore.prx",
	"flash0:/kd/loadexec.prx",
	"flash0:/kd/memab.prx",
	"flash0:/kd/memlmd.prx",
	"flash0:/kd/mesg_led.prx",
	"flash0:/kd/modulemgr.prx",
	"flash0:/kd/mscm.prx",
	"flash0:/kd/msstor.prx",
	"flash0:/kd/power.prx",
	"flash0:/kd/pspnet_resolver.prx",
	"flash0:/kd/pwm.prx",
	"flash0:/kd/registry.prx",
	"flash0:/kd/rtc.prx",
	"flash0:/kd/stdio.prx",
	"flash0:/kd/sysclib.prx",
	"flash0:/kd/syscon.prx",
	"flash0:/kd/sysmem.prx",
	"flash0:/kd/sysreg.prx",
	"flash0:/kd/systimer.prx",
	"flash0:/kd/threadman.prx",
	"flash0:/kd/usersystemlib.prx",
	"flash0:/kd/utils.prx",
	"flash0:/kd/pspcnf_tbl.txt",
	"0"
};
char *DC_150Files[] = {
	"flash0:/kd/exceptionman.prx",
	"flash0:/kd/fatmsmod.prx",
	"flash0:/kd/ge.prx",
	"flash0:/kd/hpremote.prx",
	"flash0:/kd/idstorage.prx",
	"flash0:/kd/init.prx",
	"flash0:/kd/interruptman.prx",
	"flash0:/kd/iofilemgr.prx",
	"flash0:/kd/lfatfs.prx",
	"flash0:/kd/loadcore.prx",
	"flash0:/kd/loadexec.prx",
	"flash0:/kd/memab.prx",
	"flash0:/kd/memlmd.prx",
	"flash0:/kd/mesg_led.prx",
	"flash0:/kd/modulemgr.prx",
	"flash0:/kd/mscm.prx",
	"flash0:/kd/msstor.prx",
	"flash0:/kd/pspcnf_tbl.txt",
	"flash0:/kd/pspnet_resolver.prx",
	"flash0:/kd/registry.prx",
	"flash0:/kd/rtc.prx",
	"flash0:/kd/stdio.prx",
	"flash0:/kd/sysclib.prx",
	"flash0:/kd/sysmem.prx",
	"flash0:/kd/threadman.prx",
	"flash0:/kd/usersystemlib.prx",
	"flash0:/kd/utils.prx",
	"0"
};
char *DC_340Files[] = {
	"flash0:/kd/clockgen.prx",
	"flash0:/kd/ctrl.prx",
	"flash0:/kd/display.prx",
	"flash0:/kd/dmacman.prx",
	"flash0:/kd/dmacplus.prx",
	"flash0:/kd/emc_ddr.prx",
	"flash0:/kd/emc_sm.prx",
	"flash0:/kd/gpio.prx",
	"flash0:/kd/i2c.prx",
	"flash0:/kd/lcdc.prx",
	"flash0:/kd/led.prx",
	"flash0:/kd/power.prx",
	"flash0:/kd/pwm.prx",
	"flash0:/kd/syscon.prx",
	"flash0:/kd/sysreg.prx",
	"flash0:/kd/systimer.prx",
	"0"
};
